#include "SpaceInvadersHw.hpp"

extern "C"
{
#include "main.h"
}

namespace si
{
static bool readPin(GPIO_TypeDef* port, uint16_t pin)
{
    return HAL_GPIO_ReadPin(port, pin) == GPIO_PIN_RESET;
}

void HW_Init()
{
    // GPIO/PWM init should be generated in CubeMX.
    // This function is intentionally small so it is safe to call from Model::Model().
}

InputState HW_ReadInput()
{
    InputState input;

    // Replace these macros with the real pin names generated by CubeMX.
    // Recommended: configure buttons as GPIO_Input with Pull-up.
#if defined(BTN_LEFT_GPIO_Port) && defined(BTN_LEFT_Pin)
    input.left = readPin(BTN_LEFT_GPIO_Port, BTN_LEFT_Pin);
#else
    input.left = false;
#endif

#if defined(BTN_RIGHT_GPIO_Port) && defined(BTN_RIGHT_Pin)
    input.right = readPin(BTN_RIGHT_GPIO_Port, BTN_RIGHT_Pin);
#else
    input.right = false;
#endif

#if defined(BTN_SHOOT_GPIO_Port) && defined(BTN_SHOOT_Pin)
    input.shoot = readPin(BTN_SHOOT_GPIO_Port, BTN_SHOOT_Pin);
#else
    input.shoot = false;
#endif

#if defined(BTN_START_GPIO_Port) && defined(BTN_START_Pin)
    input.start = readPin(BTN_START_GPIO_Port, BTN_START_Pin);
#else
    input.start = input.shoot;
#endif

#if defined(BTN_PAUSE_GPIO_Port) && defined(BTN_PAUSE_Pin)
    input.pause = readPin(BTN_PAUSE_GPIO_Port, BTN_PAUSE_Pin);
#else
    input.pause = false;
#endif

    return input;
}

static void ledPulse()
{
#if defined(LED_FEEDBACK_GPIO_Port) && defined(LED_FEEDBACK_Pin)
    HAL_GPIO_TogglePin(LED_FEEDBACK_GPIO_Port, LED_FEEDBACK_Pin);
#endif
}

static void buzzerOn()
{
#if defined(BUZZER_GPIO_Port) && defined(BUZZER_Pin)
    HAL_GPIO_WritePin(BUZZER_GPIO_Port, BUZZER_Pin, GPIO_PIN_SET);
#endif
}

static void buzzerOff()
{
#if defined(BUZZER_GPIO_Port) && defined(BUZZER_Pin)
    HAL_GPIO_WritePin(BUZZER_GPIO_Port, BUZZER_Pin, GPIO_PIN_RESET);
#endif
}

void HW_HandleSoundAndLed(SoundEvent event)
{
    if (event == SOUND_NONE)
    {
        buzzerOff();
        return;
    }

    ledPulse();

    // Simple GPIO buzzer feedback. For richer sound, replace by PWM on TIMx_CHy.
    buzzerOn();
    HAL_Delay(event == SOUND_GAME_OVER ? 80 : 15);
    buzzerOff();
}
}
